mk->os-50: popup component
OpiumProtocol/react-opium-components pull request #19
Opened 2020-11-17 20:06 UTC by mkunak

2020-11-19 10:27 UTC, Tima0203 requested changes

2020-11-19 10:27 UTC, Tima0203 commented on src/Components/Alert/index.tsx
> +  theme: Theme.LIGHT,
forgot to mention, make default DARK

2020-11-19 10:27 UTC, Tima0203 commented on src/Components/Button/index.tsx
> +  console.log('>>> colors:', generateThemeColors(theme))
remove console.log

2020-11-19 10:27 UTC, Tima0203 commented on src/Components/Button/index.tsx
> +  style?: CSSProperties
add "colors" prop which is 
```
type ColorScheme = {}

export type Colors = {
  [theme in Theme]?: ColorScheme
}
```
You did it right in types so we should pass {DARK: colorSchemeDark, LIGHT: colorSchemeLight}
so then for example backgroundColor = props.colors[theme]. backgroundColor
It allows us to change theme from parent component to switch colors.

2020-11-19 20:05 UTC, mkunak commented on src/Components/Button/index.tsx
> +  console.log('>>> colors:', generateThemeColors(theme))
done

2020-11-19 20:14 UTC, mkunak commented on src/Components/Alert/index.tsx
> +  theme: Theme.LIGHT,
done

2020-11-20 09:55 UTC, Tima0203 approved these changes

2020-11-20 09:55 UTC, merged